spring.application.name=twitter_Backend

server.port= 5454
spring.datasource.url=jdbc:mysql://localhost:3306/twitter
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=Shailesh1@2
